spring:
  product-datasource:
    url: jdbc:h2:mem:productdb
    username: sa
    password:
  user-datasource:
    url: jdbc:h2:mem:userdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

h2:
  console:
    enabled: true
    path: /h2-console
    settings:
      web-allow-others: false